### ISSUE TITLE
missing  Booking model 

### ISSUE THREAD

**Issue by sallner** [waza-ari/python-easyverein#15]
Hello, thanks for this nice implementation. 

I am about to automate the upload of external invoices to EasyVerein and would like to automatically associate those new invoices with existing bookings (based on the `refNumber`). This would resemble the situation, if the invoice was already present during an import of account data from the bank. 

My question is now: Was there a particular reason not to implement the booking endpoint here and would you welcome the addition to this library? Do you foresee any obstacles in this?

Do you have any other way to associate an invoice with an already imported booking via API?

**Comment by waza-ari** [comment]
Hi @sallner,

thanks for the kind words and thanks for using the library!

There is no particular reason for the Booking endpoint not to be implemented yet. The only reason is that we simply didn't need it yet and therefore I haven't spent the time to implement them. Unfortunately EasyVerein is not releasing a properly typed OpenAPI spec for their API, so adding endpoints involves quite some try&error and testing.

That being said, I don't really expect any issue there, but not sure I'll find the time in the near future to add additional endpoints. If you want to take a shot at it, I'd be more than happy to review and merge a PR though!

Best
Daniel

**Comment by waza-ari** [comment]
You're lucky, we needed the booking endpoint as well. Its been added in v1.0.1 which should be published soon.
